# Generated by Django 5.1.7 on 2025-03-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("staff", "Staff"), ("admin", "Admin")],
                default="user",
                max_length=20,
            ),
        ),
    ]
