# Generated by Django 5.1.7 on 2025-03-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="factory",
            name="level",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Уровень в иерархии"
            ),
        ),
        migrations.AddField(
            model_name="individual_entrepreneur",
            name="level",
            field=models.PositiveIntegerField(
                default=2, verbose_name="Уровень в иерархии"
            ),
        ),
        migrations.AddField(
            model_name="retail_chain",
            name="level",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Уровень в иерархии"
            ),
        ),
    ]
