# Generated by Django 5.1.7 on 2025-03-31 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0002_factory_level_individual_entrepreneur_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individual_entrepreneur",
            name="provider_factory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="individual_entrepreneur_factory_providers",
                to="supplier.factory",
                verbose_name="Поставщик завод",
            ),
        ),
        migrations.AlterField(
            model_name="individual_entrepreneur",
            name="provider_retail_chain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="individual_entrepreneur_retail_chain_providers",
                to="supplier.retail_chain",
                verbose_name="Поставщик ритейлер",
            ),
        ),
    ]
