# Generated by Django 5.1.7 on 2025-03-31 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0003_alter_individual_entrepreneur_provider_factory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="factory",
            name="provider_factory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="factory_factory_providers",
                to="supplier.factory",
                verbose_name="Поставщик завод",
            ),
        ),
        migrations.AlterField(
            model_name="factory",
            name="contacts",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factory_contacts",
                to="supplier.contacts",
                verbose_name="Контакты",
            ),
        ),
        migrations.AlterField(
            model_name="factory",
            name="products",
            field=models.ManyToManyField(
                to="supplier.products", verbose_name="Продукты"
            ),
        ),
        migrations.AlterField(
            model_name="individual_entrepreneur",
            name="contacts",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="individual_entrepreneur_contacts",
                to="supplier.contacts",
                verbose_name="Контакты",
            ),
        ),
        migrations.AlterField(
            model_name="individual_entrepreneur",
            name="products",
            field=models.ManyToManyField(
                to="supplier.products", verbose_name="Продукты"
            ),
        ),
        migrations.AlterField(
            model_name="retail_chain",
            name="contacts",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retail_chain_contacts",
                to="supplier.contacts",
                verbose_name="Контакты",
            ),
        ),
        migrations.AlterField(
            model_name="retail_chain",
            name="products",
            field=models.ManyToManyField(
                to="supplier.products", verbose_name="Продукты"
            ),
        ),
        migrations.AlterField(
            model_name="retail_chain",
            name="provider_factory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Поставщик",
                to="supplier.factory",
                verbose_name="Поставщик завод",
            ),
        ),
    ]
