# Generated by Django 5.1.7 on 2025-03-31 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0004_factory_provider_factory_alter_factory_contacts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="individual_entrepreneur",
            name="provider_Individual_entrepreneur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="individual_entrepreneur_Individual_entrepreneur_providers",
                to="supplier.individual_entrepreneur",
                verbose_name="Поставщик ИП",
            ),
        ),
        migrations.AddField(
            model_name="retail_chain",
            name="provider_retail_chain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retail_chain_retail_chain_providers",
                to="supplier.retail_chain",
                verbose_name="Поставщик сеть",
            ),
        ),
    ]
