# Generated by Django 5.1.7 on 2025-03-31 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "supplier",
            "0005_individual_entrepreneur_provider_individual_entrepreneur_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="individual_entrepreneur",
            old_name="provider_Individual_entrepreneur",
            new_name="provider_individual_entrepreneur",
        ),
    ]
