# Generated by Django 5.1.7 on 2025-03-31 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "supplier",
            "0006_rename_provider_individual_entrepreneur_individual_entrepreneur_provider_individual_entrepreneur",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="individual_entrepreneur",
            name="provider_individual_entrepreneur",
        ),
    ]
