# Generated by Django 5.1.7 on 2025-03-31 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "supplier",
            "0007_remove_individual_entrepreneur_provider_individual_entrepreneur",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="individual_entrepreneur",
            name="provider_individual_entrepreneur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="individual_entrepreneur_Individual_entrepreneur_providers",
                to="supplier.individual_entrepreneur",
                verbose_name="Поставщик ИП",
            ),
        ),
    ]
