# Generated by Django 5.1.7 on 2025-04-01 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0008_individual_entrepreneur_provider_individual_entrepreneur"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factory",
            name="provider_factory",
        ),
        migrations.RemoveField(
            model_name="individual_entrepreneur",
            name="provider_individual_entrepreneur",
        ),
        migrations.RemoveField(
            model_name="retail_chain",
            name="provider_retail_chain",
        ),
    ]
