# Generated by Django 5.1.7 on 2025-04-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0009_remove_factory_provider_factory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factory",
            name="level",
            field=models.PositiveIntegerField(
                choices=[(0, "завод")], default=0, verbose_name="Уровень в иерархии"
            ),
        ),
        migrations.AlterField(
            model_name="individual_entrepreneur",
            name="level",
            field=models.PositiveIntegerField(
                choices=[(1, "розничная сеть"), (2, "индивидуальный предприниматель")],
                default=2,
                verbose_name="Уровень в иерархии",
            ),
        ),
        migrations.AlterField(
            model_name="retail_chain",
            name="level",
            field=models.PositiveIntegerField(
                choices=[(1, "розничная сеть"), (2, "индивидуальный предприниматель")],
                default=1,
                verbose_name="Уровень в иерархии",
            ),
        ),
    ]
