# Generated by Django 5.1.7 on 2025-04-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0010_alter_factory_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factory",
            name="level",
            field=models.PositiveIntegerField(
                choices=[(0, "0")], default=0, verbose_name="Уровень в иерархии"
            ),
        ),
        migrations.AlterField(
            model_name="individual_entrepreneur",
            name="level",
            field=models.PositiveIntegerField(
                choices=[(1, "1"), (2, "2")],
                default=2,
                verbose_name="Уровень в иерархии",
            ),
        ),
        migrations.AlterField(
            model_name="retail_chain",
            name="level",
            field=models.PositiveIntegerField(
                choices=[(1, "1"), (2, "2")],
                default=1,
                verbose_name="Уровень в иерархии",
            ),
        ),
    ]
